{
    status: 200,
    statusText: 'OK',
    headers: {
      date: 'Fri, 27 Aug 2021 21:30:21 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '2981',
      connection: 'close',
      charset: 'utf-8',
      'x-pagarme-version': '2019-09-01',
      vary: 'X-HTTP-Method-Override',
      'access-control-allow-headers': 'Content-Type, Authorization, X-Requested-With, X-HTTP-Method-Override',
      'x-response-time': '583.924ms',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'GET,PUT,POST,DELETE',
      'access-control-allow-credentials': 'true',
      etag: 'W/"ba5-1H1KX5T1TZY2YUbetREC8F6iObw"',
      'x-request-id': 'c1638a69-b9a2-45d8-8adb-10818d0b6cc5',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'cf-cache-status': 'DYNAMIC',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      server: 'cloudflare',
      'cf-ray': '685866864b9f51c0-GRU'
    },
    config: {
      url: 'https://api.pagar.me/1/transactions',
      method: 'post',
      data: '{"api_key":"ak_test_3M0Hlst8ZXdLBMJuBatCO377yykhCo","amount":21000,"card_number":"4111111111111111","card_cvv":"123","card_expiration_date":"0922","card_holder_name":"Morpheus Fishburne","customer":{"external_id":"#3311","name":"Morpheus Fishburne","type":"individual","country":"br","email":"mopheus@nabucodonozor.com","documents":[{"type":"cpf","number":"00000000000"}],"phone_numbers":["+5511999998888","+5511888889999"],"birthday":"1965-01-01"},"billing":{"name":"Trinity Moss","address":{"country":"br","state":"sp","city":"Cotia","neighborhood":"Rio Cotia","street":"Rua Matrix","street_number":"9999","zipcode":"06714360"}},"shipping":{"name":"Neo Reeves","fee":1000,"delivery_date":"2000-12-21","expedited":true,"address":{"country":"br","state":"sp","city":"Cotia","neighborhood":"Rio Cotia","street":"Rua Matrix","street_number":"9999","zipcode":"06714360"}},"items":[{"id":"r123","title":"Red pill","unit_price":10000,"quantity":1,"tangible":true},{"id":"b123","title":"Blue pill","unit_price":10000,"quantity":1,"tangible":true}],"capture":false}',
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.21.1',
        'Content-Length': 1058
      },
      transformRequest: [ [Function: transformRequest] ],
      transformResponse: [ [Function: transformResponse] ],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype] {
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)],
        prefinish: [Function: requestOnPrefinish]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: 'api.pagar.me',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'api.pagar.me',
        _readableState: [ReadableState],
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular *1],
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(async_id_symbol)]: 22,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object],
        [Symbol(RequestTimeout)]: undefined
      },
      _header: 'POST /1/transactions HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 1058\r\n' +
        'Host: api.pagar.me\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: Agent {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: [Object],
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/1/transactions',
      _ended: true,
      res: IncomingMessage {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [Circular *1],
        responseUrl: 'https://api.pagar.me/1/transactions',
        redirects: [],
        [Symbol(kCapture)]: false,
        [Symbol(RequestTimeout)]: undefined
      },
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.pagar.me',
      protocol: 'https:',
      _redirectable: Writable {
        _writableState: [WritableState],
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 1058,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function (anonymous)],
        _currentRequest: [Circular *1],
        _currentUrl: 'https://api.pagar.me/1/transactions',
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array]
      }
    },
    data: {
      object: 'transaction',
      status: 'refused',
      refuse_reason: 'antifraud',
      status_reason: 'antifraud',
      acquirer_response_code: '0000',
      acquirer_name: 'pagarme',
      acquirer_id: '6129402a016a0000119f5fbb',
      authorization_code: '493694',
      soft_descriptor: null,
      tid: 13858420,
      nsu: 13858420,
      date_created: '2021-08-27T21:30:20.744Z',
      date_updated: '2021-08-27T21:30:21.138Z',
      amount: 21000,
      authorized_amount: 21000,
      paid_amount: 0,
      refunded_amount: 0,
      installments: 1,
      id: 13858420,
      cost: 0,
      card_holder_name: 'Morpheus Fishburne',
      card_last_digits: '1111',
      card_first_digits: '411111',
      card_brand: 'visa',
      card_pin_mode: null,
      card_magstripe_fallback: false,
      cvm_pin: false,
      postback_url: null,
      payment_method: 'credit_card',
      capture_method: 'ecommerce',
      antifraud_score: null,
      boleto_url: null,
      boleto_barcode: null,
      boleto_expiration_date: null,
      referer: 'api_key',
      ip: '201.9.38.128',
      subscription_id: null,
      phone: null,
      address: null,
      customer: {
        object: 'customer',
        id: 6755901,
        external_id: '#3311',
        type: 'individual',
        country: 'br',
        document_number: null,
        document_type: 'cpf',
        name: 'Morpheus Fishburne',
        email: 'mopheus@nabucodonozor.com',
        phone_numbers: [Array],
        born_at: null,
        birthday: '1965-01-01',
        gender: null,
        date_created: '2021-08-27T21:30:20.661Z',
        documents: [Array]
      },
      billing: {
        object: 'billing',
        id: 2936725,
        name: 'Trinity Moss',
        address: [Object]
      },
      shipping: {
        object: 'shipping',
        id: 1436085,
        name: 'Neo Reeves',
        fee: 1000,
        delivery_date: '2000-12-21',
        expedited: true,
        address: [Object]
      },
      items: [ [Object], [Object] ],
      card: {
        object: 'card',
        id: 'card_cksuvcfjv02rq0h9t2u7i5hjt',
        date_created: '2021-08-27T21:30:20.732Z',
        date_updated: '2021-08-27T21:30:21.183Z',
        brand: 'visa',
        holder_name: 'Morpheus Fishburne',
        first_digits: '411111',
        last_digits: '1111',
        country: 'UNITED STATES',
        fingerprint: 'cj5bw4cio00000j23jx5l60cq',
        valid: false,
        expiration_date: '0922'
      },
      split_rules: null,
      metadata: {},
      antifraud_metadata: {},
      reference_key: null,
      device: null,
      local_transaction_id: null,
      local_time: null,
      fraud_covered: false,
      fraud_reimbursed: null,
      order_id: null,
      risk_level: 'unknown',
      receipt_url: null,
      payment: null,
      addition: null,
      discount: null,
      private_label: null,
      pix_qr_code: null,
      pix_expiration_date: null
    }
  }